[BCIntegrate] Remove declaration of unused FCNLikelihood
Avoid intermittent linker errors like

libtool: link: g++ -I../../../../src/.includes -I../../../../models/base/.includes -I../../../../models/mtf/.includes -pthread -m64 -I/.hb/raidg01/sw/root/linux-ubuntu-14.04-x86_64/5.34.30/include -fopenmp -fopenmp -o .libs/runSystematics runSystematics.o  -L/.hb/raidg01/sw/root/linux-ubuntu-14.04-x86_64/5.34.30/lib ../../../../src/.libs/libBAT.so ../../../../models/base/.libs/libBATmodels.so ../../../../models/mtf/.libs/libBATmtf.so -lCore -lCint -lRIO -lNet -lHist -lGraf -lGraf3d -lGpad -lTree -lRint -lPostscript -lMatrix -lPhysics -lMathCore -lThread -lMinuit -lMathMore -lRooFitCore -lRooFit -lRooStats -lFoam -fopenmp -pthread -Wl,-rpath -Wl,/tmp/oschulz-test-bat-RIr6IQ/src/bat/BAT-1.1.0-DEV/_inst/lib
../../../../src/.libs/libBAT.so: undefined reference to `BCIntegrate::FCNLikelihood(int&, double*, double&, double*, int)'